import { useState, useEffect } from "react";
import { MobileLayout } from "@/components/layout/MobileLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { StatusBadge } from "@/components/common/StatusBadge";
import { Logo } from "@/components/common/Logo";
import { ProtectedRoute } from "@/components/common/ProtectedRoute";
import { motion, AnimatePresence } from "framer-motion";
import { 
  ArrowLeft, 
  Camera, 
  Upload, 
  Sparkles, 
  Check, 
  ChevronDown,
  Image as ImageIcon,
  X,
  Loader2,
  WifiOff,
  AlertCircle
} from "lucide-react";
import { useNavigate } from "react-router-dom";
import { cn } from "@/lib/utils";
import { saveDPR } from "@/lib/indexeddb";
import { useAppDispatch, useAppSelector } from "@/store/hooks";
import { addPendingItem } from "@/store/slices/offlineSlice";
import { usePermissions } from "@/hooks/usePermissions";
import { projectsApi } from "@/services/api/projects";
import { tasksApi } from "@/services/api/tasks";
import { dprApi } from "@/services/api/dpr";

type Step = 1 | 2 | 3 | 4 | 5;

export default function DPRPage() {
  const navigate = useNavigate();
  const dispatch = useAppDispatch();
  const { hasPermission } = usePermissions();
  const userId = useAppSelector((state) => state.auth.userId);
  const [step, setStep] = useState<Step>(1);
  const [selectedProject, setSelectedProject] = useState<string | null>(null);
  const [selectedTask, setSelectedTask] = useState<string | null>(null);
  const [photos, setPhotos] = useState<File[]>([]);
  const [photoPreviews, setPhotoPreviews] = useState<string[]>([]);
  const [notes, setNotes] = useState("");
  const [aiSummary, setAiSummary] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showSuccess, setShowSuccess] = useState(false);
  const [projects, setProjects] = useState<any[]>([]);
  const [tasks, setTasks] = useState<any[]>([]);
  const [isLoadingProjects, setIsLoadingProjects] = useState(true);
  const [isLoadingTasks, setIsLoadingTasks] = useState(false);

  // Check permission
  useEffect(() => {
    if (!hasPermission("canCreateDPR")) {
      navigate("/");
    }
  }, [hasPermission, navigate]);

  // Load projects
  useEffect(() => {
    const loadProjects = async () => {
      try {
        setIsLoadingProjects(true);
        const data = await projectsApi.getAll(1, 100);
        setProjects(data?.projects || []);
      } catch (error) {
        console.error('Error loading projects:', error);
      } finally {
        setIsLoadingProjects(false);
      }
    };
    loadProjects();
  }, []);

  // Load tasks when project is selected
  useEffect(() => {
    const loadTasks = async () => {
      if (!selectedProject) {
        setTasks([]);
        return;
      }
      try {
        setIsLoadingTasks(true);
        const data = await tasksApi.getAll(selectedProject);
        setTasks(data || []);
      } catch (error) {
        console.error('Error loading tasks:', error);
      } finally {
        setIsLoadingTasks(false);
      }
    };
    loadTasks();
  }, [selectedProject]);

  const handlePhotoUpload = () => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = 'image/*';
    input.multiple = true;
    input.onchange = (e: any) => {
      const files = Array.from(e.target.files) as File[];
      if (files.length + photos.length > 6) {
        alert('Maximum 6 photos allowed');
        return;
      }
      
      const newPhotos = [...photos, ...files];
      setPhotos(newPhotos);
      
      // Create previews
      files.forEach((file) => {
        const reader = new FileReader();
        reader.onload = (e: any) => {
          setPhotoPreviews((prev) => [...prev, e.target.result]);
        };
        reader.readAsDataURL(file);
      });
    };
    input.click();
  };

  const handleGenerateAI = async () => {
    setIsGenerating(true);
    try {
      // AI summary will be generated by backend when generateAISummary is true
      // For now, we'll just enable it for submission
      setAiSummary("AI summary will be generated upon submission");
    } catch (error) {
      console.error('Error generating AI summary:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSubmit = async () => {
    if (!selectedProject || !selectedTask) return;
    
    setIsSubmitting(true);
    
    try {
      // Submit to API with actual photo files
      await dprApi.create({
        projectId: selectedProject,
        taskId: selectedTask,
        notes: notes,
        generateAISummary: true, // Always generate AI summary
      }, photos.length > 0 ? photos : undefined);

      setShowSuccess(true);
      setTimeout(() => navigate("/"), 2000);
    } catch (error) {
      // If API fails, save to IndexedDB for offline sync
      // Convert File objects to base64 for storage
      const photoBase64: string[] = [];
      for (const photo of photos) {
        const reader = new FileReader();
        const base64 = await new Promise<string>((resolve) => {
          reader.onload = (e: any) => resolve(e.target.result);
          reader.readAsDataURL(photo);
        });
        photoBase64.push(base64);
      }
      
      const dprId = await saveDPR({
        projectId: selectedProject,
        taskId: selectedTask,
        photos: photoBase64,
        notes: notes,
        aiSummary: aiSummary,
        timestamp: Date.now(),
        createdBy: userId || "unknown",
        createdAt: new Date().toISOString(),
      });
      
      // Add to Redux offline store
      dispatch(addPendingItem({
        type: 'dpr',
        data: {
          id: dprId,
          projectId: selectedProject,
          taskId: selectedTask,
          photos: photoBase64,
          notes: notes,
          aiSummary: aiSummary,
          createdBy: userId,
          createdAt: new Date().toISOString(),
        },
      }));
      
      setShowSuccess(true);
      setTimeout(() => navigate("/"), 2000);
    } finally {
      setIsSubmitting(false);
    }
  };

  const stepTitles = {
    1: "Select Project",
    2: "Upload Photos",
    3: "Select Task",
    4: "Add Notes",
    5: "Review & Submit",
  };

  // Permission check
  if (!hasPermission("canCreateDPR")) {
    return (
      <MobileLayout role="engineer">
        <div className="min-h-screen bg-background flex items-center justify-center p-6">
          <Card className="max-w-md">
            <CardContent className="p-6 text-center space-y-4">
              <AlertCircle className="w-12 h-12 text-destructive mx-auto" />
              <h2 className="font-display text-xl font-semibold text-foreground">
                Access Denied
              </h2>
              <p className="text-sm text-muted-foreground">
                You don't have permission to create DPRs. Only Site Engineers can create Daily Progress Reports.
              </p>
              <Button onClick={() => navigate("/")} className="w-full">
                Go to Dashboard
              </Button>
            </CardContent>
          </Card>
        </div>
      </MobileLayout>
    );
  }

  return (
    <MobileLayout role="engineer">
      <div className="min-h-screen bg-background">
        {/* Header */}
        <div className="sticky top-0 z-10 bg-background/95 backdrop-blur-xl border-b border-border/50 py-4 pl-0 pr-4 safe-area-top">
          <div className="flex items-center gap-0 relative">
            <div className="absolute left-0 mt-3">
              <Logo size="md" showText={false} />
            </div>
            <div className="flex-1 flex flex-col items-center justify-center">
              <h1 className="font-display font-semibold text-lg">Create DPR</h1>
              <p className="text-xs text-muted-foreground">{stepTitles[step]}</p>
            </div>
            <div className="absolute right-0">
              <StatusBadge status="offline" label="Offline" />
            </div>
          </div>

          {/* Progress */}
          <div className="flex gap-1 mt-4">
            {[1, 2, 3, 4, 5].map((s) => (
              <div
                key={s}
                className={cn(
                  "flex-1 h-1 rounded-full transition-all duration-300",
                  s <= step ? "bg-primary" : "bg-muted"
                )}
              />
            ))}
          </div>
        </div>

        {/* Success Overlay */}
        <AnimatePresence>
          {showSuccess && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 z-50 bg-background/95 flex items-center justify-center"
            >
              <motion.div
                initial={{ scale: 0.8, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0.8, opacity: 0 }}
                className="text-center space-y-4"
              >
                <motion.div
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  transition={{ type: "spring", stiffness: 200, damping: 15 }}
                  className="w-20 h-20 mx-auto rounded-full bg-success/20 flex items-center justify-center"
                >
                  <Check className="w-10 h-10 text-success" />
                </motion.div>
                <h2 className="font-display text-2xl font-bold text-foreground">DPR Submitted!</h2>
                <p className="text-muted-foreground">Your report has been saved offline</p>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Content */}
        <div className="p-4 space-y-4">
          {/* Step 1: Select Project */}
          {step === 1 && (
            <div className="space-y-3 animate-fade-up">
              {isLoadingProjects ? (
                <div className="flex items-center justify-center py-12">
                  <Loader2 className="w-8 h-8 animate-spin text-primary" />
                </div>
              ) : projects.length === 0 ? (
                <Card>
                  <CardContent className="p-8 text-center">
                    <p className="text-muted-foreground">No projects available</p>
                  </CardContent>
                </Card>
              ) : (
                projects.map((project) => (
                  <Card
                    key={project._id}
                    className={cn(
                      "cursor-pointer transition-all duration-200",
                      selectedProject === project._id && "border-primary shadow-glow-sm"
                    )}
                    onClick={() => {
                      setSelectedProject(project._id);
                      setStep(2);
                    }}
                  >
                    <CardContent className="p-4 flex items-center justify-between">
                      <span className="font-medium">{project.name}</span>
                      <ChevronDown className={cn(
                        "w-5 h-5 text-muted-foreground transition-transform",
                        selectedProject === project._id && "-rotate-90"
                      )} />
                    </CardContent>
                  </Card>
                ))
              )}
            </div>
          )}

          {/* Step 2: Upload Photos */}
          {step === 2 && (
            <div className="space-y-4 animate-fade-up">
              <Card variant="gradient">
                <CardContent className="p-6">
                  <div className="grid grid-cols-3 gap-3 mb-4">
                    {photoPreviews.map((preview, index) => (
                      <div key={index} className="relative aspect-square rounded-xl overflow-hidden bg-muted">
                        <img src={preview} alt={`Photo ${index + 1}`} className="w-full h-full object-cover" />
                        <button 
                          className="absolute top-1 right-1 p-1 rounded-full bg-background/80"
                          onClick={() => {
                            setPhotos(photos.filter((_, i) => i !== index));
                            setPhotoPreviews(photoPreviews.filter((_, i) => i !== index));
                          }}
                        >
                          <X className="w-3 h-3" />
                        </button>
                      </div>
                    ))}
                    {photos.length < 6 && (
                      <button
                        onClick={handlePhotoUpload}
                        className="aspect-square rounded-xl border-2 border-dashed border-border flex flex-col items-center justify-center gap-2 text-muted-foreground hover:border-primary hover:text-primary transition-colors"
                      >
                        <Camera className="w-6 h-6" />
                        <span className="text-xs">Add</span>
                      </button>
                    )}
                  </div>
                  <div className="flex gap-3">
                    <Button variant="outline" className="flex-1" onClick={handlePhotoUpload}>
                      <Camera className="w-4 h-4 mr-2" />
                      Camera
                    </Button>
                    <Button variant="outline" className="flex-1" onClick={handlePhotoUpload}>
                      <Upload className="w-4 h-4 mr-2" />
                      Gallery
                    </Button>
                  </div>
                </CardContent>
              </Card>
              
              <Button 
                className="w-full" 
                size="lg"
                onClick={() => setStep(3)}
                disabled={photos.length === 0 || !selectedProject}
              >
                Continue
              </Button>
            </div>
          )}

          {/* Step 3: Select Task */}
          {step === 3 && (
            <div className="space-y-3 animate-fade-up">
              {isLoadingTasks ? (
                <div className="flex items-center justify-center py-12">
                  <Loader2 className="w-8 h-8 animate-spin text-primary" />
                </div>
              ) : tasks.length === 0 ? (
                <Card>
                  <CardContent className="p-8 text-center">
                    <p className="text-muted-foreground">No tasks available for this project</p>
                  </CardContent>
                </Card>
              ) : (
                tasks.map((task) => (
                  <Card
                    key={task._id}
                    className={cn(
                      "cursor-pointer transition-all duration-200",
                      selectedTask === task._id && "border-primary shadow-glow-sm"
                    )}
                    onClick={() => {
                      setSelectedTask(task._id);
                      setStep(4);
                    }}
                  >
                    <CardContent className="p-4 flex items-center justify-between">
                      <span className="font-medium">{task.title}</span>
                      <StatusBadge 
                        status={task.status === "completed" ? "success" : task.status === "in-progress" ? "info" : "pending"} 
                        label={task.status.replace("-", " ")} 
                      />
                    </CardContent>
                  </Card>
                ))
              )}
            </div>
          )}

          {/* Step 4: Add Notes */}
          {step === 4 && (
            <div className="space-y-4 animate-fade-up">
              <Card variant="gradient">
                <CardHeader className="pb-3">
                  <CardTitle className="text-base">Add Notes (Optional)</CardTitle>
                </CardHeader>
                <CardContent>
                  <textarea
                    value={notes}
                    onChange={(e) => setNotes(e.target.value)}
                    placeholder="Enter any additional notes about today's work..."
                    className="w-full h-32 p-3 rounded-xl bg-muted/50 border border-border/50 text-foreground placeholder:text-muted-foreground resize-none focus:outline-none focus:ring-2 focus:ring-primary/50"
                  />
                </CardContent>
              </Card>

              {/* AI Generate Button */}
              <Button
                variant="outline"
                className="w-full border-primary/50 text-primary"
                onClick={handleGenerateAI}
                disabled={isGenerating}
              >
                {isGenerating ? (
                  <>
                    <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4 mr-2" />
                    Generate AI Summary
                  </>
                )}
              </Button>

              {aiSummary && (
                <Card variant="glow" className="animate-fade-up">
                  <CardContent className="p-4">
                    <div className="flex items-center gap-2 mb-3">
                      <Sparkles className="w-4 h-4 text-primary" />
                      <span className="text-sm font-medium text-primary">AI Generated Summary</span>
                    </div>
                    <textarea
                      value={aiSummary}
                      onChange={(e) => setAiSummary(e.target.value)}
                      className="w-full h-32 p-3 rounded-xl bg-muted/50 border border-border/50 text-foreground resize-none focus:outline-none focus:ring-2 focus:ring-primary/50"
                    />
                  </CardContent>
                </Card>
              )}

              <Button 
                className="w-full" 
                size="lg"
                onClick={() => setStep(5)}
              >
                Continue to Review
              </Button>
            </div>
          )}

          {/* Step 5: Review & Submit */}
          {step === 5 && (
            <div className="space-y-4 animate-fade-up">
              <Card variant="gradient">
                <CardHeader className="pb-3">
                  <CardTitle className="text-base">Review DPR</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="p-3 rounded-xl bg-muted/50">
                    <span className="text-xs text-muted-foreground">Project</span>
                    <p className="font-medium text-foreground">
                      {projects.find(p => p._id === selectedProject)?.name || "Unknown Project"}
                    </p>
                  </div>
                  
                  <div className="p-3 rounded-xl bg-muted/50">
                    <span className="text-xs text-muted-foreground">Task</span>
                    <p className="font-medium text-foreground">
                      {tasks.find(t => t._id === selectedTask)?.title || "Unknown Task"}
                    </p>
                  </div>

                  <div className="p-3 rounded-xl bg-muted/50">
                    <span className="text-xs text-muted-foreground mb-2 block">Photos ({photos.length})</span>
                    <div className="flex gap-2 overflow-x-auto pb-2">
                      {photoPreviews.map((preview, index) => (
                        <img 
                          key={index} 
                          src={preview} 
                          alt={`Photo ${index + 1}`}
                          className="w-16 h-16 rounded-lg object-cover shrink-0"
                        />
                      ))}
                    </div>
                  </div>

                  {(notes || aiSummary) && (
                    <div className="p-3 rounded-xl bg-muted/50">
                      <span className="text-xs text-muted-foreground">Summary</span>
                      <p className="text-sm text-foreground mt-1">
                        {aiSummary || notes}
                      </p>
                    </div>
                  )}
                </CardContent>
              </Card>

              <div className="flex items-center gap-2 p-3 rounded-xl bg-warning/10 border border-warning/30">
                <WifiOff className="w-4 h-4 text-warning shrink-0" />
                <span className="text-sm text-warning">Will sync when online</span>
              </div>

              <Button 
                className="w-full" 
                size="lg"
                variant="glow"
                onClick={handleSubmit}
                disabled={isSubmitting}
              >
                {isSubmitting ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    Submitting...
                  </>
                ) : (
                  <>
                    <Check className="w-5 h-5" />
                    Submit DPR
                  </>
                )}
              </Button>
            </div>
          )}
        </div>
      </div>
    </MobileLayout>
  );
}
